<div class="field mobile required">
    <label for="mobile" class="label">
        <span><?= /* @noEscape */ __("Mobile") ?></span>
    </label>
    <div class="control">
        <input type="text"
               name="mobile"
               title="<?= /* @noEscape */ __("Mobile") ?>"
               class="input-text"
               data-validate="{required:true}"
               id="mobile">
    </div>
</div>