<?php

$helper = $block->helper(Tochat\Whatsapp\Helper\Data::class);

$order = $block->getOrder();

$message = $helper->getRecentMessage($order->getId());

if (!$helper->isActive()) { return;
}
?>
<div class="whatsapp-block">
    <button class='whatsapp' 
        data-phone='<?= $block->escapeHtmlAttr($order->getBillingAddress()->getTelephone()) ?>'
        data-status='<?= $block->escapeHtmlAttr($order->getStatus()) ?>'
        data-id='<?= $block->escapeHtmlAttr($order->getId()) ?>'><?= /* @noEscape */ __("Click to Chat") ?></button>
    <?php if ($message): ?>
    <p><?= /* @noEscape */ __("Last message sent %1:", $helper->timeElapsedString($message->getCreatedAt())) ?></p>
    <p><strong><?= /* @noEscape */ __("WhatsApp") ?>:</strong><?= $block->escapeHtml($message->getMessage()) ?></p>
    <?php endif; ?>
</div>